// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

declare namespace Contentful {
  export interface ICalendarFields {
    /** date */
    date: string;

    /** isHoliday */
    isHoliday: boolean;
  }

  export interface ICalendar extends Entry<ICalendarFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "calendar";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export interface IFishFields {
    /** name */
    name: string;

    /** description */
    description: string;

    /** thumbnail */
    thumbnail?: Asset | undefined;

    /** isLive */
    isLive: boolean;
  }

  export interface IFish extends Entry<IFishFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "fish";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export interface IServiceFields {
    /** title */
    title: string;

    /** background */
    background: Asset;

    /** description0 */
    description0: string;

    /** description1 */
    description1?: string | undefined;

    /** description2 */
    description2?: string | undefined;

    /** description3 */
    description3?: string | undefined;

    /** description4 */
    description4?: string | undefined;

    /** order */
    order: number;
  }

  export interface IService extends Entry<IServiceFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "service";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export interface ISetouchiFishFields {
    /** name */
    name: string;

    /** thumbnail */
    thumbnail?: Asset | undefined;

    /** description */
    description?: string | undefined;

    /** seasonStart0 */
    seasonStart0: number;

    /** seasonEnd0 */
    seasonEnd0: number;

    /** seasonStart1 */
    seasonStart1?: number | undefined;

    /** seasonEnd1 */
    seasonEnd1?: number | undefined;
  }

  export interface ISetouchiFish extends Entry<ISetouchiFishFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "setouchiFish";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export interface ITopFields {
    /** title */
    title: string;

    /** description */
    description: string;

    /** thumbnail */
    thumbnail: Asset;

    /** order */
    order: number;
  }

  export interface ITop extends Entry<ITopFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "top";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export type CONTENT_TYPE =
    | "calendar"
    | "fish"
    | "service"
    | "setouchiFish"
    | "top";

  export type LOCALE_CODE = "ja";

  export type CONTENTFUL_DEFAULT_LOCALE_CODE = "ja";
}

export as namespace Contentful;
export = Contentful;
